### ISSUE TITLE
Worker install: fuse: failed to open /dev/fuse: Permission denied

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#118]
This is my attempt to install a sandboxed worker on a host(aichallengebeta.hypertriangle.com), hosted at sshvm.com:

```
contest@aichallengebeta:~/aichallenge/setup$ sudo ./worker_setup.py
Executing: dpkg --print-architecture
Install tools on Ubuntu version:natty arch:amd64.
Warning: This script is meant to be run as root and will make changes to the configuration of the machine it is run on.
Are you sure you want to continue (yes/no)? [no] yes
Update and upgrade system before rest of setup? [yes] no
Only install packages, do no additional setup? [no]
Contest username? [contest]
Contest root directory? [/home/contest]
Directory of source repository? [/home/contest/aichallenge]
Create bot jails? [yes]
API Base url? [hypertriangle.com] aichallengebeta.hypertriangle.com
Worker API key? [] b4d8e9b8df1400fd98a13abedd79642d
Install startup cronjob? [no]
Immediately run worker start script at end of setup? [no]
Run setup as configured above (yes/no)? [no] yes
Executing: apt-get install -y curl unzip
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version.
unzip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Executing: apt-get install -y openssh-server htop screen vim
Reading package lists... Done
Building dependency tree
Reading state information... Done
openssh-server is already the newest version.
screen is already the newest version.
vim is already the newest version.
htop is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Executing: apt-get install -y debootstrap schroot unionfs-fuse gcc
Reading package lists... Done
Building dependency tree
Reading state information... Done
debootstrap is already the newest version.
gcc is already the newest version.
unionfs-fuse is already the newest version.
schroot is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Executing: useradd -g jailusers -d /home/jailuser jailuser1
Executing: iptables -A OUTPUT -m owner --uid-owner jailuser1 -j DROP
Executing: chown jailuser1:jailusers /srv/chroot/jailuser1/home/home/jailuser
Executing: chown :jailkeeper /srv/chroot/jailuser1
Executing: chmod g=rwx /srv/chroot/jailuser1
Executing: mount /srv/chroot/jailuser1/root
fuse: failed to open /dev/fuse: Permission denied
Traceback (most recent call last):
File "./worker_setup.py", line 392, in <module>
    main(sys.argv)
File "./worker_setup.py", line 381, in main
    setup_jailusers(opts)
File "./worker_setup.py", line 246, in setup_jailusers
    create_jail_user("jailuser%s" % (user_num,))
File "./worker_setup.py", line 222, in create_jail_user
    run_cmd("mount %s" % (os.path.join(jail_dir, "root"),))
File "/home/contest/aichallenge/setup/install_tools.py", line 68, in run_cmd
    raise CmdError(cmd, status)
install_tools.CmdError: Error 1 returned from mount /srv/chroot/jailuser1/root
```

I will proceed reinstalling without a sandbox.

**Comment by amstan** [comment]
This is something funny with sshvm, it's not capable of doing fuse without a special kernel.
