### ISSUE TITLE
worker.py: server_info["game_options"][:] TypeError: unhashable type

### ISSUE THREAD

**Issue by amstan** [aichallenge/aichallenge#119]
I was peacefully trying to get worker.py running, and then suddenly a wild error appears:

```
contest@aichallengebeta:~/aichallenge/worker$ python worker.py -d -t
2011-05-23 06:26:29,787 - 28078 - INFO - Getting task 1
2011-05-23 06:26:29,794 - 28078 - INFO - Received task: {u'submission_id': u'2', u'task': u'compile'}
2011-05-23 06:26:29,794 - 28078 - INFO - Downloading 2...
2011-05-23 06:26:29,803 - 28078 - INFO - Unpacking /home/contest/compiled/tmpMuap09...
2011-05-23 06:26:29,816 - 28078 - INFO - unnzip status: 0
2011-05-23 06:26:29,819 - 28078 - INFO - Compiling 2 
2011-05-23 06:26:30,442 - 28078 - INFO - {'errors': ['std.date and std.dateparse have been scheduled for deprecation. Please use std.datetime instead.\n']}
2011-05-23 06:26:30,443 - 28078 - INFO - Detected language: D
2011-05-23 06:26:30,443 - 28078 - INFO - Running functional test for 2
2011-05-23 06:26:30,444 - 28078 - ERROR - Traceback (most recent call last):
File "worker.py", line 457, in task
    if not self.compile(submission_id, True):
File "worker.py", line 317, in compile
    if not run_test or self.functional_test(submission_id):
File "worker.py", line 361, in functional_test
    options = server_info["game_options"][:]
TypeError: unhashable type
```

**Comment by amstan** [comment]
I tried using .copy() or removing [:] entirely, but i just get a lot of these:

```
2011-05-23 07:00:54,257 - 30094 - INFO - Getting task infinity + 1
2011-05-23 07:00:54,266 - 30094 - INFO - Received task: {u'task': u'game', u'submissions': [u'8', u'7', u'5', u'6', u'3'], u'map_filename': u'symmetric_maps/symmetric_4.map', u'matchup_id': u'9'}
2011-05-23 07:00:54,266 - 30094 - INFO - Running game 9...
2011-05-23 07:00:54,267 - 30094 - INFO - http://aichallengebeta.hypertriangle.com//api_game_result.php?api_key=b4d8e9b8df1400fd98a13abedd79642d
2011-05-23 07:00:54,267 - 30094 - INFO - Posting hash: 13754559723f4fa9bc7d5125fa160326
2011-05-23 07:00:54,276 - 30094 - INFO - Bad json from server during post result:


2011-05-23 07:00:54,277 - 30094 - INFO - Getting task infinity + 1
2011-05-23 07:00:54,286 - 30094 - INFO - Received task: {u'task': u'game', u'submissions': [u'8', u'7', u'5', u'6', u'3'], u'map_filename': u'symmetric_maps/symmetric_4.map', u'matchup_id': u'9'}
2011-05-23 07:00:54,286 - 30094 - INFO - Running game 9...
2011-05-23 07:00:54,287 - 30094 - INFO - http://aichallengebeta.hypertriangle.com//api_game_result.php?api_key=b4d8e9b8df1400fd98a13abedd79642d
2011-05-23 07:00:54,287 - 30094 - INFO - Posting hash: c0c3d96a4c5cbd3aa9c043a83d9c25cd
2011-05-23 07:00:54,295 - 30094 - INFO - Bad json from server during post result:


2011-05-23 07:00:54,296 - 30094 - INFO - Getting task infinity + 1
2011-05-23 07:00:54,305 - 30094 - INFO - Received task: {u'task': u'game', u'submissions': [u'8', u'7', u'5', u'6', u'3'], u'map_filename': u'symmetric_maps/symmetric_4.map', u'matchup_id': u'9'}
2011-05-23 07:00:54,305 - 30094 - INFO - Running game 9...
2011-05-23 07:00:54,306 - 30094 - INFO - http://aichallengebeta.hypertriangle.com//api_game_result.php?api_key=b4d8e9b8df1400fd98a13abedd79642d
2011-05-23 07:00:54,306 - 30094 - INFO - Posting hash: bd655c497e443018cb20b78d22b11dbb
2011-05-23 07:00:54,315 - 30094 - INFO - Bad json from server during post result:
```

**Comment by McLeopold** [comment]
This should be fixed with the latest worker updates today.
