### ISSUE TITLE
Python 2.6 syntax error in ant.py

### ISSUE THREAD

**Issue by medains** [aichallenge/aichallenge#221]
```
ants$ ./play_one_game.sh
Traceback (most recent call last):
  File "./playgame.py", line 14, in <module>
    from ants import Ants
  File "/home/cameigh/Personal/Development/Google-AI/Ants/git/aichallenge/ants/ants.py", line 1117
    orientations = [[(ants[0].loc, 0, {i: i for i in range(self.num_players)})]]
                                              ^
SyntaxError: invalid syntax
```

I got this running by replacing "i:i for i in range(self.num_players)" with "0:0" but I'm not very familiar with python so I don't know what effect that will have.

**Comment by jmcarthur** [comment]
Fixed in 66b94de
